server:
  port: ${SERVER_PORT:8092}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

# Choose ONE of the security modes by activating a profile
# 1) JWT via JWK Set URI from AuthIdentityService (profile: jwt)

---
management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    secret: ${JWT_SECRET:change-this-super-long-secret-please-change-me-0123456789}
    validity-ms: ${JWT_VALIDITY_MS:3600000}
#spring:
#  config:
#    activate:
#      on-profile: jwt
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json
